//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proga1920
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeroflot
    {
        public int номер_рейса { get; set; }
        public string пункт_назначения { get; set; }
        public Nullable<System.DateTime> время_вылета { get; set; }
        public Nullable<System.DateTime> время_прибытия { get; set; }
        public Nullable<int> количество_свободных_мест { get; set; }
        public string тип_самолета { get; set; }
        public Nullable<int> вместимость_самолета { get; set; }
    }
}
