//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proga1920
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int код { get; set; }
        public Nullable<int> логин { get; set; }
        public Nullable<int> пароль { get; set; }
        public string доступ { get; set; }
        public string почта { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
    }
}
